# Generated by Django 3.1.6 on 2023-03-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_remove_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=100),
        ),
    ]
