# Generated by Django 3.1.6 on 2023-04-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_product_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='grams',
        ),
    ]
