# Generated by Django 3.1.6 on 2023-04-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20230412_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grams',
            field=models.FloatField(default=100),
        ),
    ]
